name: build
on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "10.19.0"
      # - run: npm ci
      # - run: npm run build
      # - run: npm run tslint
      # - run: npm run test
      # - run: npm run publish-coverage
      # - run: npm run package
      #if a tag, create a github release
      - if: startsWith(github.ref, 'refs/tags/v')
        run: echo "create release"
      #if a non-pre-release tag, 
      - if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-beta.') == false
        run: echo "not beta release so publish to store"

